server: 
  servlet: 
    context-path: /sz
  port: 8091

spring: 
  datasource:
    url: jdbc:mysql://192.168.0.101:3306/sz
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      filters: stat
      max-active: 20
      initial-size: 5
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  http: 
    encoding: 
      charset: utf-8
    jackson: 
      date-format: yyyy-mm-dd hh:mm:ss 
      timezone: asia/shanghai
    resources: 
      chain: 
        enabled: true
  cache: 
    type: REDIS
  redis: 
    database: 0
    hostName: 192.168.43.216
    port: 6379
    # Login password of the redis server.
    password: 
    timeout: 0
    pool: 
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1
    sentinel: 
      # Name of Redis server.
      master:
      # Comma-separated list of host:port pairs. 
      nodes:
  dubbo: 
    scan: com.sizatn.ssd.dubbo
    application: 
      name: provider
    registry: 
      protocol: zookeeper
      address: 200.20.2.160
      port: 2181
    protocol: 
      name: dubbo
      port: 20880
    
logging: 
  config: classpath:logback-boot.xml
